server:
  port: 9002

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user-registration
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/